global:
  scrape_interval: 15s
  scrape_timeout: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '192.168.35.104:9093'

rule_files:
  - 'heap_memory_alert.yml'
  - 'high_cpu_alert.yml'

scrape_configs:
  - job_name: 'basic'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.35.104:8080']
