global:
  scrape_interval: 15s
  scrape_timeout: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '13.124.245.126:9093'

rule_files:
  - 'heap_memory_alert.yml'
  - 'high_cpu_alert.yml'

scrape_configs:
  - job_name: 'basic'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['13.124.245.126:8080', '13.209.222.30:8080']
